server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #main:
  #  allow-bean-definition-overriding: true
  freemarker:
    cache: false
  config:
    import:
      - optional:classpath:custom.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_ID}
    password: ${LOCAL_DB_PW}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
  batch:
    initialize-schema: always
    job:
      enabled: false
spring.thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false


enable_lazy_load_no_trans: true

logging:
  level:
    com.project.metasu: DEBUG


    #url:  jdbc:mysql://localhost:3306/metasu?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    #username: root
    #password: a123
    
#아이템 사진 업로드 경로 - 서버 올릴시 수정 필요
file:
  dir:   C:\Users\CHOIYURIM\Desktop\MetanetInternProj\metasu\src\main\resources\static\uploadItemImg
  lecture_dir: C:\Users\CHOIYURIM\Desktop\MetanetInternProj\metasu\src\main\resources\static\uploadItemImg
  course_dir: C:\Users\CHOIYURIM\Desktop\MetanetInternProj\metasu\src\main\resources\static\uploadItemImg